### ISSUE TITLE
Invalid AWS region for af-south-1 region

### ISSUE THREAD

**Issue by gerhard-vniekerk** [openshift/oadp-operator#749]
When installing the OADP in AWS in the af-south-1 region the aws registry pod is throwing the following error:

time="2022-07-06T07:35:37.626456083Z" level=info msg="debug server listening :5001"
panic: invalid region provided: af-south-1

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x10b67c0, 0xc000536390, 0xc000451500, 0x0)
	/remote-source/src/github.com/docker/distribution/registry/handlers/app.go:126 +0x2e41
github.com/docker/distribution/registry.NewRegistry(0x10b67c0, 0xc00045b3b0, 0xc000451500, 0x5, 0x0, 0x0)
	/remote-source/src/github.com/docker/distribution/registry/registry.go:106 +0x1c9
github.com/docker/distribution/registry.glob..func1(0x1716860, 0xc00046e400, 0x1, 0x1)
	/remote-source/src/github.com/docker/distribution/registry/registry.go:64 +0x187
github.com/spf13/cobra.(*Command).execute(0x1716860, 0xc00046e3d0, 0x1, 0x1, 0x1716860, 0xc00046e3d0)
	/remote-source/deps/gomod/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1716ac0, 0x0, 0xd52ca0, 0xc0000b2058)
	/remote-source/deps/gomod/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/remote-source/deps/gomod/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/remote-source/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d

Seems like it does not like the as-south-1 region
[log-oadp-dpa-instance-1-aws-registry-547565bd6c-9r98p.log](https://github.com/openshift/oadp-operator/files/9052681/log-oadp-dpa-instance-1-aws-registry-547565bd6c-9r98p.log)
.

**Comment by kaovilai** [comment]
Newer regions will be added in the 1.1 release.

If you need to use them now you may be able to override in DPA
Workaround, use latest registry image from upstream

```yaml
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero-sample
spec:
  unsupportedOverrides:
    registryImageFqin: "distribution/distribution"
```

Please track any updates on this issue at https://issues.redhat.com/browse/OADP-553

**Comment by kaovilai** [comment]
There's also another open github issue on this https://github.com/openshift/oadp-operator/issues/730

**Comment by kaovilai** [comment]
Fixed with #743

**Comment by gerhard-vniekerk** [comment]
I have set the following:

  unsupportedOverrides:
    registryImageFqin: "distribution/distribution"

But I am still getting the following error:

time="2022-08-11T09:42:37.986094011Z" level=info msg="debug server listening localhost:5001"
panic: Invalid region provided: af-south-1

goroutine 1 [running]:
panic(0xb7dbc0, 0xc4204820c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/handlers.NewApp(0x1066800, 0xc4203c56b0, 0xc420149c00, 0x1066800)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:123 +0x3908
github.com/docker/distribution/registry.NewRegistry(0x7f0b1ac83758, 0xc4203c56b0, 0xc420149c00, 0xe, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
github.com/docker/distribution/registry.glob..func1(0x108e180, 0xc42035feb0, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108e180, 0xc42035fe60, 0x1, 0x1, 0x108e180, 0xc42035fe60)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108e320, 0xc420201f40, 0xc4200001a0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d

**Comment by kaovilai** [comment]
Latest release distribution/distribution is using AWS sdk 1.15.11

af-south-1 was added to AWS sdk in 1.34.2

Try distribution/distribution:edge

**Comment by gerhard-vniekerk** [comment]
Great, thanks, that worked. Just a question on the next release date. When will V1.1 be released?

**Comment by shubham-pampattiwar** [comment]
@gerhard-vniekerk OADP 1.1 is going to be released on September 1st.
